version: '3.8'

services:
  # Next.js Application - Direct Access (No Nginx)
  sinergia-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL=http://localhost:9080/api
        - NEXT_PUBLIC_APP_URL=http://localhost:9080
        - NEXT_PUBLIC_ERP_ENV=PROD
        - ERP_BASE_URL=https://sinergia.digitalasiasolusindo.com
        - ERP_DEV_BASE_URL=https://sinergiadev.digitalasiasolusindo.com
    container_name: sinergia-sales-web
    ports:
      - "9080:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:9080/api
      - NEXT_PUBLIC_APP_URL=http://localhost:9080
      - NEXT_PUBLIC_ERP_ENV=PROD
      - ERP_BASE_URL=https://sinergia.digitalasiasolusindo.com
      - ERP_DEV_BASE_URL=https://sinergiadev.digitalasiasolusindo.com
      - SESSION_TIMEOUT_MINUTES=60
      - AUTH_CHECK_INTERVAL_MINUTES=5
      - COOKIE_MAX_AGE_MINUTES=120
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - sinergia-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - redis

  # Redis for Session Management
  redis:
    image: redis:7-alpine
    container_name: sinergia-redis
    ports:
      - "6380:6379"  # Changed to avoid conflict
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - sinergia-network
    command: redis-server --appendonly yes

networks:
  sinergia-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
