version: '3.8'

services:
  # Next.js Application
  sinergia-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sinergia-sales-web
    ports:
      - "9080:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:9080/api
      - NEXT_PUBLIC_APP_URL=http://localhost:9080
      - NEXT_PUBLIC_ERP_ENV=PROD
      - ERP_BASE_URL=https://sinergia.digitalasiasolusindo.com
      - ERP_DEV_BASE_URL=https://sinergiadev.digitalasiasolusindo.com
      - SESSION_TIMEOUT_MINUTES=60
      - AUTH_CHECK_INTERVAL_MINUTES=5
      - COOKIE_MAX_AGE_MINUTES=120
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - sinergia-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx Reverse Proxy (Optional) - Disabled for now due to SSL issues
  # nginx:
  #   image: nginx:alpine
  #   container_name: sinergia-nginx
  #   ports:
  #     - "9080:80"
  #     - "9443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   depends_on:
  #     - sinergia-web
  #   restart: unless-stopped
  #   networks:
  #     - sinergia-network

  # Redis for Session Management (Optional)
  redis:
    image: redis:7-alpine
    container_name: sinergia-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - sinergia-network
    command: redis-server --appendonly yes

networks:
  sinergia-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
